# Changes here will be overwritten by Copier
_commit: v1.6.0
_src_path: gh:DragonBishop/python-copier-template-ds
github_actions: true
include_module: false
include_notebooks: true
include_reports: true
project_name: cyclistic_case_study
project_type: data_analysis
python_version: 3.14.7
use_rumdl: true
